== Patch-to-CLS Aggregation and Attention

A major unanswered question concerns how local patch information is aggregated into the global CLS representation. The patch analysis identifies cases where anomalous patches form locally coherent and distinctive structures even when the corresponding CLS representation provides relatively weak normal-defect separation. The current distance-based analysis cannot determine how this local information is propagated through the transformer. Future work could therefore examine attention between anomalous patches, surrounding normal patches, and the CLS token to determine which local regions influence the final global representation and why some anomaly information appears to be weakened during aggregation.

This could also provide a more direct use of the transformer architecture for interpretability. Attention patterns could be compared with known segmentation masks to investigate whether patches corresponding to anomalous regions receive increased influence within later transformer layers. Such analysis could help explain contrasting cases where strong local anomaly structure does not translate directly into strong global separation. This question is particularly relevant because the availability of both patch and CLS representations, together with the attention mechanism, was one of the motivations for using DINOv2 in this work.

== Fine-Tuning and Representation Geometry

The correlations identified between patch-level and CLS-level representation properties also motivate further experimentation during fine-tuning. @section:cls_patch_corr identifies associations between local patch structure and desirable CLS geometry, but these correlations do not establish that deliberately improving a patch-level property will cause an improvement in the global representation. Future work could test this relationship by tracking patch and CLS metrics throughout fine-tuning and examining whether deliberate changes to the local representation produce corresponding changes in CLS geometry and anomaly-detection performance.

The results also suggest that useful patch representations should not necessarily be reduced to maximising normal-defect separation or forcing all patches belonging to the same group into a single compact region. Future fine-tuning experiments could instead investigate objectives that preserve meaningful local variation while improving the resulting global representation. Patch-level geometry could be tracked alongside CLS Davies-Bouldin Index, Calinski-Harabasz Index, Separation Ratio, and AUROC to determine how different training objectives alter both representation structure and final anomaly-detection performance. This would also allow generic contrastive objectives such as InfoNCE@infonce to be evaluated based on how they affect the underlying geometry rather than only their final AUROC.

== Alternative Representations

The DINOv2 layer analysis also identified relatively similar performance between the final transformer layers. Future work could investigate whether earlier representations provide useful inputs for alternative prediction or projection heads during fine-tuning, and whether combining information from multiple layers provides advantages over using only the final CLS representation as seen from the works of PaDiM @padim and Patchcore @patchcore. This could additionally explore whether small reductions in anomaly-detection performance are justified by reduced computational cost when using an earlier exit from the transformer