= Discussion

As discussed in the Results, the proposed ellipsoidal approach does not outperform the Mahalanobis baseline overall. The additional flexibility introduced by modelling multiple local regions of the normal embedding space therefore does not, by itself, translate into improved anomaly-detection performance. However, this does not necessarily indicate that local modelling is ineffective. Performance may instead depend on how regions are constructed, how covariance is estimated within them, and how local regions are combined to represent the overall normal distribution.

The current method follows a relatively greedy local construction strategy, where regions are identified and expanded independently to cover portions of the embedding space. A single global Mahalanobis model represents the opposite extreme, describing the entire normal distribution using one mean and covariance estimate. The stronger baseline performance suggests that the global representation may provide a more statistically stable starting point than constructing the normal space from many independently grown local regions.

The use of a fixed neighbourhood proportion across categories may also contribute to this sensitivity. Although 5% provided a practical compromise during validation, differences in embedding density and structure mean that the same proportion may produce overly local regions for some categories and overly broad regions for others. An adaptive neighbourhood size based on local embedding density may therefore provide a more suitable starting point for region construction.

This motivates an alternative interpretation of the region-growing strategy used in Cloud of Spheres@cloudspheres. In its supervised setting, regions can be expanded until they encounter negative samples, providing a natural boundary between classes. In the unsupervised setting considered here, only normal training samples are available, meaning that locally grown regions must instead infer suitable boundaries from the structure of the normal embeddings. Rather than beginning with small K-Nearest Neighbour-based regions and progressively expanding them, the process could therefore be inverted: a large global normal region could first be estimated and then contracted, divided, or refined where the embedding structure indicates excessive variation. Local modelling would then act as a refinement of the global representation rather than a replacement for it.

The dimensionality of the embedding space presents an additional challenge. DINOv2 ViT-S/14@dinov2 produces 384-dimensional embeddings, while the ellipsoids formed by the proposed algorithm frequently have much lower effective rank. Dividing the training distribution into many small regions reduces the number of samples available for estimating each covariance matrix and can therefore produce rank-deficient local models. This effect varies between categories because some contain fewer normal training samples than the embedding dimensionality, while others contain more. Consequently, low effective rank may reflect insufficient local sample support in some cases and genuine lower-dimensional embedding structure in others. Dimensionality reduction, smaller embedding models, or regularised covariance estimation could therefore be investigated to determine whether a lower-dimensional representation improves stability.

The covariance-sharing heuristic described in @section:low_support_ell further highlights this issue. Ellipsoids containing insufficient samples borrow covariance information from better-supported regions. While this avoids unstable covariance estimates, repeated borrowing may cause several local regions to inherit similar covariance structures. In the extreme, the model can begin to resemble a fragmented global Mahalanobis representation, but without the advantage of estimating that covariance from the full set of normal samples.

A possible future approach would therefore combine both global and local modelling. A large, well-supported ellipsoid could first capture the dominant normal structure, while samples excluded from this region could be grouped using methods such as K-means@kmeans and represented by smaller local ellipsoids. These secondary regions could estimate their own covariance when sufficiently supported or model only variation not captured by the primary region. Such an approach would retain the ability to describe multiple modes of normal behaviour while introducing local complexity only where the data indicates that it is required.