== Other Established Baselines

Two established anomaly-detection methods are considered alongside the DINOv2 baseline: PaDiM @padim and PatchCore @patchcore. Both approaches use pretrained convolutional neural networks to extract representations from normal training images, but differ substantially in how these representations are modelled and subsequently used for anomaly detection. Comparing their architectures with the DINOv2-based approach provides additional context for the choice of representation and anomaly-scoring strategy used in this work.

PaDiM, or Patch Distribution Modeling, extracts features from multiple levels of a pretrained CNN and models the normal representation independently at each spatial patch position. For every position $(i,j)$, features observed across the normal training images are represented using a multivariate Gaussian distribution. At inference, the Mahalanobis distance between a test patch embedding and its corresponding learned normal distribution is used as the anomaly score. This allows PaDiM to account for both the average normal representation and the covariance between feature dimensions, while combining information from different semantic levels of the CNN. Because only the learned Gaussian parameters must be retained after training, its inference memory requirements are independent of the number of original training images. The method achieves an AUROC of 97.1%, exceeding the selected DINOv2 baseline of 95.8%. Its distribution-based representation of normal data is also conceptually related to the local distribution modelling investigated later in this work.

#align(center)[
  #figure(
    image("../images/padim.png"),
    caption: [Architecture of PaDiM]
  )
]

PatchCore instead preserves representative examples of normal patch representations within a memory bank. Features are extracted from intermediate layers of an ImageNet-pretrained CNN rather than relying on the deepest representation. The authors argue that intermediate features retain more local information while avoiding some of the task-specific bias associated with deeper ImageNet classification features. Local neighbourhood aggregation is additionally applied to increase the receptive field of each patch representation without reducing the spatial resolution of the feature map. Features from two adjacent intermediate feature hierarchies are then combined to construct the normal patch-feature memory bank. \
As storing every normal patch would result in substantial memory and inference costs, PatchCore reduces this memory bank using greedy coreset subsampling. Rather than selecting patches randomly, the coreset attempts to retain representative coverage of the original normal feature space. At inference, each test patch is compared with its nearest neighbour in the resulting memory bank, with large distances indicating representations that are poorly supported by the observed normal data. The image-level anomaly score is primarily determined by the most anomalous patch, with additional re-weighting based on the neighbourhood surrounding its closest memory-bank representation. PatchCore achieves an AUROC of 99.1%, substantially exceeding the DINOv2 baseline and approaching perfect image-level ranking performance on MVTec AD.

#align(center)[
  #figure(
    image("../images/patchcore.png"),
    caption: [Architecture of Patchcore]
  )
]
Both approaches differ from the DINOv2 baseline used in this work. PaDiM and PatchCore primarily operate on local feature maps extracted from pretrained CNNs, whereas DINOv2 is a Vision Transformer that directly provides both local patch tokens and a global CLS representation. The baseline developed here performs image-level anomaly detection using the CLS embedding and models the normal representation using distance-based scoring methods such as Mahalanobis distance and KNN. PaDiM instead models a separate Gaussian distribution for each spatial feature position, while PatchCore retains a representative collection of normal local features and performs nearest-neighbour comparison against this memory.

Despite the stronger reported AUROC of these specialised approaches, DINOv2 provides several properties that are particularly useful for the objectives of this work. The availability of both patch and CLS representations allows the relationship between local anomaly information and the final global representation to be investigated directly, while the transformer architecture provides a basis for future experiments examining how attention influences this aggregation. DINOv2 also provides a general pretrained representation upon which alternative normal-space modelling approaches can be developed, allowing improvements beyond the initial distance-based baseline to be investigated while retaining access to the underlying embedding geometry.

There is also an important distinction in how representation efficiency is approached. PaDiM reduces embedding dimensionality through random dimension selection, which can preserve anomaly-detection performance while reducing computational requirements. However, retaining similar AUROC does not establish what representational information has been discarded. This is less important for the baseline comparison considered here, where final anomaly-detection performance is the primary concern, but becomes more relevant when considering the interpretability of the learned representation, which is a greater focus of this work. Understanding which properties of the representation contribute to anomaly detection, rather than only whether performance is retained after compression, therefore provides an additional motivation for examining the DINOv2 embedding space directly.