=== Embedding Projections 

The preceding patch statistics describe category-level behaviour by aggregating measurements across defective images. However, individual defect types can differ substantially in their spatial extent and visual characteristics. This section therefore examines selected patch projections at the defect-type level to provide qualitative context for the statistical results. Screw, metal nut, and wood are considered as case studies because they exhibit different behaviours in the preceding analysis, allowing local anomaly structure, defect coverage, and variation in normal patch representations to be examined more directly.

#figure(
  image("../images/screw_patch_plot.png", width: 112%),
  caption: [Example of different types for the Screw category]
) <fig:screw_plot>

The patch projections in @fig:screw_plot provide a visual example of the improved local structure observed for screw in the preceding statistical analysis. Rather than 
treating defective screw samples as a single group, the projections show how individual defect types are represented relative to the normal patches within each image For manipulated_front, where the tip of the screw is defective, most anomalous patches form a relatively localised region near the edge of the normal patch distribution, although one anomalous patch lies much closer to the normal patch structure. This partial overlap is qualitatively consistent with the comparatively low Calinski-Harabasz Score reported for screw in @table:patch_cluster_metrics, since the defective patches are not uniformly separated from the surrounding normal representation.

The scratch and thread defects exhibit somewhat different behaviour. In these images, the anomalous region spans a slightly larger number of patches, which generally form more compact local groups relative to the surrounding normal patches. This is particularly visible for scratch_neck, thread_side, and thread_top. The greater local compactness of these defective patch groups is qualitatively consistent with the lower Davies-Bouldin value observed for screw at the patch level in @table:patch_cluster_metrics, indicating lower within-group dispersion relative to the separation between normal and anomalous patches.

These examples help explain the contrast between the patch and CLS results discussed previously. Screw anomalies can produce locally distinctive patch representations even when only a small number of patches are affected. When these local representations contribute to the global CLS token, however, their influence may be small relative to the much larger amount of normal screw information present in the image. The patch projections therefore provide qualitative support for the earlier observation that locally coherent anomaly information can be present even where normal and defective CLS embeddings remain difficult to distinguish.

#figure(
  image("../images/metal_nut_patch_plot.png", width: 110%),
  caption: [Example of different types for the Metal-Nut category]
) <fig:metal_nut>

The patch projections in @fig:metal_nut provide an example of how the number and distribution of anomalous patches may influence the category-level statistics observed previously. The flip defect is particularly notable, as defective patches occupy a substantially larger proportion of the projected space than for the other defect types. Despite this large anomalous region, many of these patches remain close to the normal patch distribution, which may contribute to the Separation Ratio of approximately 1.00 (0.9997) observed in @table:inter_distances. This is consistent with the earlier observation that a spatially large structural defect does not necessarily produce locally distinctive patch representations. Furthermore, flip defects account for approximately 20% of the defective metal nut test samples in @fig:defect_type_example, meaning that their patch-level behaviour may have a meaningful influence on the category-level statistic. However, because the reported Separation Ratio aggregates all defect types, the contribution of flip cannot be isolated from the current analysis. Computing the metric separately for each defect type would be required to determine how strongly this behaviour contributes to the overall metal nut result.


#figure(
  image("../images/wood_patch_plot.png", width: 110%),
  caption: [Example of different types for the Wood category]
) <fig:wood>

The patch projections in @fig:wood provide a possible explanation for the comparatively poor Normal Test/Train retention ratio observed in @table:intra_distances. Wood achieves the lowest ratio of all categories at 0.8228, with the Normal Intra-Cluster Distance decreasing from 28.6674 for the training patches to 23.5885 for the normal patches within defective test images. Although wood has a relatively uniform overall appearance, its local texture contains substantial variation in the orientation, spacing, and contrast of the grain. Different grain patterns may therefore cause normal patches to occupy relatively dispersed regions of the embedding space, while differences in the grain represented within the training and test samples could contribute to the relatively large change in compactness between the two distributions. This behaviour can also be linked back to the CLS statistics in @table:cls_stats, where wood exhibits the poorest Normal Inter-Cluster result and the highest Normal Intra-Cluster Distance (18.9459). Together, the poor patch retention ratio and comparatively dispersed CLS representation suggest that natural variation in wood grain may affect the stability of both the local patch embeddings and the resulting global representation.

Despite this variation within the normal representation, wood still achieves a relatively high Mahalanobis AUROC of 0.944 in @table:mal_aurocs. This may be partly explained by the structure of its defective patch embeddings. Wood achieves a comparatively low patch-level Davies-Bouldin Index of 1.4002 and a high Calinski-Harabasz Index of 40.1426, together with a Separation Ratio of 1.4054, indicating that its anomalous patches generally remain well separated from the normal reference while forming relatively coherent local groups. The projections in @fig:wood support this interpretation, with the different wood defect types generally producing compact anomalous regions that remain distinguishable from the surrounding normal patches. Therefore, although natural variation in wood grain may reduce the stability of the normal representation between training and test samples, the defects themselves can still introduce sufficiently distinctive local changes to support strong anomaly-detection performance.