= Introduction

In conventional classification, a sample $x in RR^n$ is assigned to one of $K$ classes based on properties shared by samples belonging to that class. However, representing a class becomes more difficult when its distribution is heterogeneous or multimodal. A single global decision region may then become overly broad, covering areas of the feature space that do not accurately represent the observed samples. This is particularly relevant to unsupervised anomaly detection, where defective examples may be unavailable during training and the normal distribution must be modelled without prior knowledge of possible anomalies.

Representation-learning models map visually complex images into embedding spaces in which similarity can be analysed geometrically. However, normal samples are not necessarily well represented by a single centroid, sphere, or global covariance estimate. Different normal appearances may occupy separate or elongated regions, causing a global model either to exclude valid normal samples or include unsupported areas of the embedding space.

The _Cloud of Spheres_ method proposed by #cite(<cloudspheres>, form: "prose") addresses complex class structure using multiple connected spherical regions rather than a single global region. Its supervised formulation constructs a connected set of spheres around the target class through mixed-integer nonlinear optimisation while minimising the number of required regions. This provides an explicit geometric representation capable of describing nonlinear and non-convex class boundaries.

This paper extends this approach by proposing a _Cloud of Ellipsoids_ for unsupervised anomaly detection. Rather than constraining each local region to be isotropic, ellipsoids adapt to the covariance and local geometry of the representation space, allowing different variation and orientation along each axis. Normal space can therefore be represented by multiple locally fitted regions without requiring defective training examples.

DINOv2 @dinov2 is used to generate the representation space, despite not being trained specifically for anomaly detection, with the proposed method evaluated on the 15 object and texture categories of MVTec AD @mvtec2019. The primary objective is to determine whether the natural variation within normal images forms local structure that can be captured effectively using multiple ellipsoidal regions, particularly where a single global distribution provides an inadequate description of the embedding space. This local representation also provides a more explicit geometric interpretation of normality by relating each sample to specific regions of the learned space rather than only to a single global score. Performance is compared with simpler global distance-based anomaly-detection approaches at the image level.